# Generated by Django 2.1.5 on 2019-02-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_questions_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='attempts',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
